name: 'Google Cloud Setup'

description: 'Action for setting up Google Cloud'

inputs:
  version:
    default: 'latest'
    description: 'A string representing the version or version constraint of the Cloud SDK (`gcloud`) to install (e.g. `"290.0.1"` or `">= 197.0.1"`). The default value is `"latest"`, which will always download and install the latest available Cloud SDK version.'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🔵🔴🟡🟢 ☁️ Setup Google Cloud
      uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
      with:
        version: ${{ inputs.version }}
