name: 'Publish GitHub release'

description: 'Action to publish a GitHub release'

inputs:
  allow-empty-changelog:
    default: true
    description: 'Allow empty changelog'
    required: true
    type: boolean
  changelog-file:
    default: 'CHANGELOG.md'
    description: 'Changelog file'
    required: true
    type: string
  draft-release:
    default: false
    description: 'Draft release'
    required: true
    type: boolean
  github-token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string
  pre-release:
    default: false
    description: 'Pre-release'
    required: true
    type: boolean
  tag-prefix-regex:
    description: 'Tag prefix regex'
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: 📝🚀 GitHub Release
      uses: anton-yurchenko/git-release@ec9c5b5c36b27eaffc628785b9183eae54601200 # v6.0.0
      env:
        ALLOW_EMPTY_CHANGELOG: '${{ inputs.allow-empty-changelog }}'
        CHANGELOG_FILE: '${{ inputs.changelog-file }}'
        DRAFT_RELEASE: '${{ inputs.draft-release }}'
        GITHUB_TOKEN: '${{ inputs.github-token }}'
        PRE_RELEASE: '${{ inputs.pre-release }}'
        TAG_PREFIX_REGEX: '${{ inputs.tag-prefix-regex }}'
