name: 'Checkout'

description: 'Action for checking out a repository'

inputs:
  fetch-depth:
    default: '0'
    description: 'Depth for fetching'
    required: true
    type: string
  token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 📂 Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
