name: 'Checkout'

description: 'Action for checking out a repository'

inputs:
  fetch-depth:
    default: '0'
    description: 'Depth for fetching'
    required: true
    type: string
  token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 📂 Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
