name: 'Checkout'

description: 'Action for checking out a repository'

inputs:
  fetch-depth:
    default: '0'
    description: 'Depth for fetching'
    required: true
    type: string
  token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 📂 Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
