name: 'Checkout'

description: 'Action for checking out a repository'

inputs:
  fetch-depth:
    default: '0'
    description: 'Depth for fetching'
    required: true
    type: string
  token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 📂 Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
