name: 'Checkout'

description: 'Action for checking out a repository'

inputs:
  fetch-depth:
    default: '0'
    description: 'Depth for fetching'
    required: true
    type: string
  token:
    default: ${{ github.token }}
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 📂 Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
