name: 'Upload SARIF'

description: 'Upload SARIF file'

inputs:
  sarif_file:
    description: 'Path to SARIF file'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4
      with:
        sarif_file: ${{ inputs.sarif_file }}
