name: 'Upload SARIF'

description: 'Upload SARIF file'

inputs:
  sarif_file:
    description: 'Path to SARIF file'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4
      with:
        sarif_file: ${{ inputs.sarif_file }}
