name: 'Upload SARIF'

description: 'Upload SARIF file'

inputs:
  sarif_file:
    description: 'Path to SARIF file'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@d1ba80a13dd99fba24a470575428917156a28b43 # v4
      with:
        sarif_file: ${{ inputs.sarif_file }}
