name: 'Authenticate to Google Cloud'

description: 'Action for authenticating to Google Cloud'

inputs:
  project-id:
    description: 'Google Cloud project ID'
    required: true
    type: string
  workload-identity-provider:
    description: 'Workload Identity Provider'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🔵🔴🟡🟢 🔑 Authenticate to Google Cloud
      uses: google-github-actions/auth@7b53cdc2a387814ed14eec026287aac689ae8c9b # v2.1.9
      with:
        project_id: ${{ inputs.project-id }}
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
