name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    default: '3.10'
    description: 'Python version'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
      with:
        python-version: ${{ inputs.python-version }}
