name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    default: '3.10'
    description: 'Python version'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ inputs.python-version }}
