name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    default: 'artifact'
    description: 'Name of the artifact'
    required: true
    type: string
  path:
    description: 'Path to the artifact'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⤴️💽 Upload artifact
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
