name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    default: 'artifact'
    description: 'Name of the artifact'
    required: true
    type: string
  path:
    description: 'Path to the artifact'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⤴️💽 Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
