name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    default: 'artifact'
    description: 'Name of the artifact'
    required: true
    type: string
  path:
    description: 'Path to the artifact'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⤴️💽 Upload artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
