name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    default: 'artifact'
    description: 'Name of the artifact'
    required: true
    type: string
  path:
    description: 'Path to the artifact'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⤴️💽 Upload artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
