name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: 🛠️ Build and push 🐳 Docker images
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
