name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: 🛠️ Build and push 🐳 Docker images
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
