name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: 🛠️ Build and push 🐳 Docker images
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
