name: 'Find GitHub pull request'

description: 'Action to find a GitHub pull request'

inputs:
  branch:
    description: 'Branch name'
    required: true
    type: string

outputs:
  number:
    description: "Pull request number"
    value: ${{ steps.find-pull-request.outputs.number }}

runs:
  using: "composite"

  steps:
    - name: ⤴️ Find GitHub pull request
      id: find-pull-request
      uses: juliangruber/find-pull-request-action@952b3bb1ddb2dcc0aa3479e98bb1c2d1a922f096 # v1.10.0
      with:
        branch: ${{ inputs.branch }}
