name: 'Find GitHub pull request'

description: 'Action to find a GitHub pull request'

inputs:
  branch:
    description: 'Branch name'
    required: true
    type: string

outputs:
  number:
    description: "Pull request number"
    value: ${{ steps.find-pull-request.outputs.number }}

runs:
  using: "composite"

  steps:
    - name: ⤴️ Find GitHub pull request
      id: find-pull-request
      uses: juliangruber/find-pull-request-action@33d46d4ff90884bb23aaead16044125daaf733d8 # v1.11.0
      with:
        branch: ${{ inputs.branch }}
