name: 'Setup Java'

description: 'Action for setting up Java'

inputs:
  distribution:
    default: 'zulu'
    description: 'Distribution'
    required: true
    type: string
  java-version:
    default: '21'
    description: 'Java version'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🍵 Set up Java
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
