name: 'Setup Xcode'

description: 'Action for setting up Xcode'

inputs:
  xcode-version:
    default: 'latest-stable'
    description: 'Xcode version'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 🛠️🍎 Set up Xcode
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
      if: startsWith(matrix.os, 'macos-')
      with:
        xcode-version: ${{ inputs.xcode-version }}
