name: Auto Approve PR

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: ✅ Auto Approve
        uses: JavierSegoviaCordoba/Actions/github/pull-request/auto-approve@26f6391e1f01d0edf49d9cf298a78803d6f5290d # main
        with:
          github-token: '${{ secrets.TOKEN_GITHUB_ACTION }}'
