name: Auto Approve PR

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: ✅ Auto Approve
        uses: JavierSegoviaCordoba/Actions/github/pull-request/auto-approve@0ebfbcef13e7b87d8af7dd38f6bc575316adbfab # main
        with:
          github-token: '${{ secrets.TOKEN_GITHUB_ACTION }}'
