name: Auto Approve PR

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: ✅ Auto Approve
        uses: JavierSegoviaCordoba/Actions/github/pull-request/auto-approve@31dba23ba5922a4c61bfc31993ff6280c861ec22 # main
        with:
          github-token: '${{ secrets.TOKEN_GITHUB_ACTION }}'
